apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-app
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: rolling-app
  template:
    metadata:
      labels:
        app: rolling-app
    spec:
      containers:
        - name: http-go
          image: heechankim/rolling-app:v3
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-app
spec:
  selector:
    app: rolling-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
