apiVersion: v1
kind: ReplicationController
metadata:
  name: rolling-app-v1
spec:
  replicas: 3
  template:
    metadata:
      name: rolling-app
      labels:
        app: rolling-app
    spec:
      containers:
        - image: heechankim/rolling-app:v1
          name: http-go
---

apiVersion: v1
kind: Service
metadata:
  name: rolling-app
spec:
  type: LoadBalancer
  selector:
    app: rolling-app
  ports:
    - port: 80
      targetPort: 8080
