apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-cont
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
