apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling-app
  template:
    metadata:
      name: changed-name
      labels:
        app: rolling-app
    spec:
      containers:
        - name: http-go
          image: heechankim/rolling-app:v1
          ports:
            - containerPort: 8080
              protocol: TCP
